name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  baseUrl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: './'
      with:
        appName: 'TestApp'
        baseUrl: https://auspost.com.au/shop/
